application: modmaven
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /data
  static_dir: data
  mime_type: application/json

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

# Handler for module page
- url: /modpage/?
  script: main.app

# Handler for logging out
- url: /logout/?
  script: main.app

# Handler for front page
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: 2.6
